### ISSUE TITLE
Hacker Hours group in Boise, ID

### ISSUE THREAD

**Issue by compscirunner** [HackerHours/hackerhours.org#149]
Hello, 
We have formed a hacker hours group in Boise, ID. 
http://www.meetup.com/hackerhoursboise/
http://hackerhoursboise.github.io/

We would love to be added to your list. 
Regards, 
Dave

**Comment by afeld** [comment]
Whoa, that's the coolest thing I've heard all day! So many questions!
- What's the backstory?
- How did you hear about Hacker Hours?
- Did you happen to see the [DIY Guide](http://hackerhours.org/diy-guide.html)? Was it helpful?
- I had an idea a while back to make http://hackerhours.org/ work for the various Hacker Hours groups (https://github.com/afeld/hackerhours.org/issues/9), though it looks like you've created your own site, which is great. Is there any way this site could be of more use to your group?

Thanks for letting us know!
