### ISSUE TITLE
create a logo

### ISSUE THREAD

**Issue by afeld** [HackerHours/hackerhours.org#25]
would be great to be able to give to other groups for cross-promotion, instead of the stolen image I've been using as the Meetup group's avatar :grin:

**Comment by AnneTheAgile** [comment]
I love to noodle logos. I see right now there is no logo, just nice formatted lettering, right? 
I wonder what icons , symbols are appropriate. I've made logos for other groups I've been in... Thoughts so far are ; 
coffee ; sort of like a coffee klatch, modern style
lock and key ; idea of 
worker , like on your blog; solving problems
sitting at an old fashioned CRT with airplane scarf flying in the wind (old ad I saw and loved).

None of these initial thoughts seem good enough to get me going, but maybe you have remarks!
Also I see your blog announcing  Hacker Hours was Sep 25, 2011, Sunday. Do you count that day or the next Thursday 6pm as when you were founded? 

http://hackerhours.org/

**Comment by afeld** [comment]
> I see right now there is no logo, just nice formatted lettering, right?

Correct. There are a few different "assets" in use, none of which I am strongly attached to:
- The text version on [the homepage](http://hackerhours.org/) in [Merriweather](http://www.google.com/fonts/specimen/Merriweather)
- The [banner](https://github.com/afeld/hackerhours.org/blob/gh-pages/assets/hacker_hours_banner.png), at the top of [the Meetup page](http://www.meetup.com/hackerhours/) ([Illustrator file](https://github.com/afeld/hackerhours.org/blob/gh-pages/assets/hacker_hours_banner.ai))
- The [miner](https://github.com/afeld/hackerhours.org/blob/gh-pages/assets/miner.jpeg) illustration, which I use for the meetup logo
  - I probably picked it at the time because it harkens back to the Ruby ["pickaxe" book](https://pragprog.com/book/ruby/programming-ruby)
  - Unfortunately I don't have rights for it

> I wonder what icons , symbols are appropriate

There is some unresolved discussion in https://github.com/afeld/hackerhours.org/pull/22, but this group has transitioned from being about experts helping novices, to being a community where people can get together, talk tech, and get advice.

I like that the banner image shows a bunch of people putting their heads (well, shoulders) together, so maybe it could play off of that idea.

> coffee ; sort of like a coffee klatch

Huh, never heard that word before. It's nice because we were running Hacker Hours out of a coffee shop for a while, and it conveys the communal aspect.

> worker , like on your blog; solving problems

The worker (and I would say the pickaxe, specifically) is nice because it can stand for breaking problems down into smaller pieces.

> an old fashioned CRT with airplane scarf flying in the wind

While that could be a fun image, I don't think it says much about the group.

> I see your blog announcing Hacker Hours was Sep 25, 2011, Sunday. Do you count that day or the next Thursday 6pm as when you were founded?

Hmm, I never really thought about the exact date, but I suppose I would go with Thurs 9/29/11.

**Comment by afeld** [comment]
New design from @SiberianCharm, @jeremiak, and _____!

![screen shot 2015-04-27 at 12 16 52 am](https://cloud.githubusercontent.com/assets/86842/7341610/be7035a6-ec72-11e4-9022-05bdd1982021.png)

http://codepen.io/anon/pen/XbJpRa

I played around with the proportions a bit, mostly making the clock slightly smaller and its border thinner. Let me know what you think!

![screen shot 2015-04-27 at 12 16 21 am](https://cloud.githubusercontent.com/assets/86842/7341606/aaa9ca3c-ec72-11e4-9382-a2fb2942a8f8.png)

http://codepen.io/anon/pen/EjaWBY?editors=110

**Comment by siberiancharm** [comment]
looks good :)

**Comment by afeld** [comment]
What are your thoughts about how to incorporate it? I can take a screenshot and make it the group image on the Meetup page, but less obvious about how to use it on the standalone site.

**Comment by siberiancharm** [comment]
yes, share the screenshot and solicit landing pg layout suggestions from
front-end leaning Hackers Hours / Code Buddies members and user flows from
the ux inclined

**Comment by jeremiak** [comment]
hey @afeld and @SiberianCharm feel free to take a [look at my first go](http://jeremiak.github.io/hackerhours.org/) at an implementation (#116)

**Comment by emiclark** [comment]
I like it. I think narrower vertical feet and playing with different shades of gray may help keep it lighter, social and feeling less rigid. The serif treatment (which now, after doing one looks a bit much).
![hhlogo2](https://cloud.githubusercontent.com/assets/10621575/7406244/2930126a-eecd-11e4-8678-baac5db5a144.jpg)

**Comment by jeremiak** [comment]
I like the different shade of gray & keeping the ascenders on the H thinner but I agree that the serifs feel like they're a bit too much.

**Comment by afeld** [comment]
Responding to an email from @SiberianCharm:

> Who is our main audience

People who are learning to code, and people that would be willing to help them.

> what is our main message?

Hacker Hours is a great place to get help, work among a supportive group, and to meet people. More brainstorming in https://github.com/afeld/hackerhours.org/pull/22.

> What stretch goals/new customers/members do we want to attract? 

I suppose people that are too shy to ask for help, and potential mentors who might not normally make time for it.

> Who is our "competition"?

I mean, I suppose the other [related groups](http://hackerhours.org/related-groups.html)...but I don't really care about trying to out-market them or anything. I suppose the thing we are fighting is people saying "oh, I've been meaning to go to that" who never do. Lots of friends are in that boat. Since we don't have special workshops or speakers at each one, there is no sense of urgency to attend (unless you need help that week).

**Comment by siberiancharm** [comment]
Thank you. Ideas percolating --- soon to be expressed both verbally and
pictorially.

**Comment by Penderis** [comment]
![hacker hours logo_test nighthours](https://cloud.githubusercontent.com/assets/3405854/8272667/74806050-184c-11e5-9bf9-87ba16ff3f82.png)
Not sure if this still a issue but figured I would like to try a nice logo for a change as well. Will make a repo with files people can continue as they wish.

**Comment by afeld** [comment]
@Penderis **Wow** nice, thanks! Curious how you came across this issue?

The hourglass idea is interesting – wonder if we could use that same idea, but with less detail? The vertical bars being skyscrapers is cool, though I don't want Hacker Hours to seem city-centric.

Anyone else have opinions about it? Thanks again!

**Comment by siberiancharm** [comment]
Looks confusingly like a wine glass, so reads like HappyHours to me. Also a
bit busy, needs more simpler clearer shapes- think about it as a tiny icon
in a browser tab, as well as a 2.5 or 3" diameter sticker on a laptop. A
great mark needs to work well in a variety of sizes and applications.

**Comment by Penderis** [comment]
@afeld heard about hacker hours on a podcast , like on twitter , saw the image on your feed noticed the link is a github issue. 

As for the logo sample, what I was thinking if that helps 
1. Time element obviously , clock just seemed to generic and could not decide what the actual time would be so that was a deal breaker.
2. hourglass was decided on this is the simplified shape the other involved trying to get curly braces to create it , still trying.
3. the semi-colon is the only representation to code, also needs further work but could represent the person 
4. not to be city centric just happen to be the H at the back do create the feel of lights being on past office hours. I should try convey this better.

Just a few thoughts , I will try a better version , any any critique is welcome, should probly ask if it ok if I do try to complete this even as personal project? 

I noticed you animated the other one beautifully and think even simplifying the hourglass to just contain sand that in the animation the sand can go to the bottom become the underscore then type out hacker hours. Just a thought.

**Comment by Penderis** [comment]
@SiberianCharm Thank you, will note that a more solid shape would be a better fit.

**Comment by siberiancharm** [comment]
:)

**Comment by afeld** [comment]
The hourglass idea is interesting to me, visually. Has a nice shape. If I were getting super analytical about it, it would seem that an hourglass is _constraining_ time rather than "making time available" for getting help, but that may be overthinking it.

> you animated the other one beautifully and think even simplifying the hourglass to just contain sand that in the animation

Ooh, that could be cool.

---

Design by committee is hard :wink:

**Comment by Penderis** [comment]
I added a repo where I can put stuff https://github.com/Penderis/design-itch . You can view the tests easier will attach screenshots of the 2 well 2.4 new ones I played with.

![screenshot 2015-06-25 21 52 53](https://cloud.githubusercontent.com/assets/3405854/8364457/cba3ba5c-1b86-11e5-83f7-f90a0eb0e0ad.png)
![screenshot 2015-06-25 21 52 55](https://cloud.githubusercontent.com/assets/3405854/8364462/cea4dff6-1b86-11e5-9390-64274960917e.png)

**Comment by Penderis** [comment]
Oh the one with the lotsa icons is more each one is a replacement for the other to see the diff between each. also small to large is 32px till 256px display.

**Comment by siberiancharm** [comment]
Aaahhh, that looks like HackerDna :)

**Comment by Penderis** [comment]
haha yes a unfortunate side effect in this case, infinity just not coming through
