### ISSUE TITLE
Add list of tutors

### ISSUE THREAD

**Issue by afeld** [HackerHours/hackerhours.org#4]
Had a bunch of people looking/offering (see "JS Tutors?" thread [on mailing list](http://nyc.hackerhours.org/messages/archive/)) - would be nice to make a list on the site with skill lists and have it link to their email or Meetup profile page to contact them.  Also, include instructions about how to add oneself as a tutor.

**Comment by PeterBell** [comment]
Maybe just suggest a standard format and directory where someone can list name, skills, contact mechanism and value (e.g. email:x@y.com or skype:myskypeuser) - maybe as a json or text file that some js could list? That way you could just accept pull requests for new instructors? Only annoying thing is that it'd also take a PR to update or delete your file (firstname_lastname.json in tutors/ directory?), but still it'd be a fairly lightweight way to try it out. Thoughts?

**Comment by afeld** [comment]
Totally what I was thinking :-)

**Comment by afeld** [comment]
Doing this through the wiki is gonna be easiest - just made a page for it.

https://github.com/afeld/hackerhours.org/wiki/Tutors

Will try to go through the backlog of people that have previously shared their info on the mailing list and populate it.
- [x] link to Wiki (or maybe tutor page specifically) from homepage
