### ISSUE TITLE
make title more obviously clickable

### ISSUE THREAD

**Issue by afeld** [HackerHours/hackerhours.org#5]
thanks @kbaum for the suggestion

**Comment by jamesaanderson** [comment]
A hover color and/or effect might make it more obvious.

**Comment by kbaum** [comment]
I think we can leave the whole thing clickable and also have a button smack in the middle that says "meetup info" or something like that.

**Comment by ritvikgautam** [comment]
For this we can simply add a hover effect in the style sheet, isn't?
I can help.
