### ISSUE TITLE
Open Source Workshop

### ISSUE THREAD

**Issue by Patdel** [HackerHours/hackerhours.org#80]
Hi, I did a pull request a while ago to participate in this workshop with my girlfriend and I didn't get any response. Is there any way I can know if I got in? It seems that I am not part of the participants' list. I would appreciate if you could give me some guidance on this issue.
Best regards,
Patricio Calderon

**Comment by afeld** [comment]
Hmm, I don't see it:

https://github.com/afeld/hackerhours.org/issues?utf8=%E2%9C%93&q=involves%3APatdel

but no worries. Mind each submitting a pull request for your own RSVP?
